apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3JkMTIz # base64 for "rootpassword123"
  MYSQL_PASSWORD: dG9kb2FwcDEyMw==      # base64 for "todoapp123"
