apiVersion: v1
kind: Secret
metadata:
  name: todoapp-secrets
type: Opaque
data:
  # mysql+pymysql://todoapp:todoapp123@mysql-service.todo-app:3306/todoapp
  database-url: bXlzcWwrcHlteXNxbDovL3RvZG9hcHA6dG9kb2FwcDEyM0BteXNxbC1zZXJ2aWNlLnRvZG8tYXBwOjMzMDYvdG9kb2FwcA==
