apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todoapp-monitor
  labels:
    app: todoapp
    release: prometheus
spec:
  selector:
    matchLabels:
      app: todoapp     
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
