apiVersion: v1
kind: Service
metadata:
  name: todoapp-service
  labels:
    app: todoapp
spec:
  selector:
    app: todoapp
  ports:
  - port: 80
    name: http
    targetPort: 5000
  type: NodePort
